<a href="https://colab.research.google.com/github/sprerak48/Autonomous-tagging-using-Deep-Learning/blob/Sanket/Final%20Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import pandas as pd
import numpy as np

In [0]:
dataset_filename = "Test100.csv"
data = pd.read_csv(dataset_filename, index_col=0)
datax = data.loc[: , :]


In [4]:
import nltk
nltk.download('stopwords')
from nltk.tokenize import RegexpTokenizer
from nltk.corpus import stopwords
from nltk.corpus import wordnet
from nltk.stem import WordNetLemmatizer
nltk.download('wordnet')

wordnet_lemmatizer = WordNetLemmatizer()
tokenizer = RegexpTokenizer(r'[a-z]+')
stop_words = set(stopwords.words('english'))

def preprocess(document):
    document = document.lower() # Convert to lowercase
    words = tokenizer.tokenize(document) # Tokenize
    words = [w for w in words if not w in stop_words] # Removing stopwords
    # Lemmatizing
    for pos in [wordnet.NOUN, wordnet.VERB, wordnet.ADJ, wordnet.ADV]:
        words = [wordnet_lemmatizer.lemmatize(x, pos) for x in words]
    return " ".join(words)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Unzipping corpora/wordnet.zip.


In [0]:
datax.to_csv("Test.csv",index=False)

In [6]:
import pandas as pd
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from numpy import array
from keras.models import load_model
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.model_selection import train_test_split

newtest = "Test100.csv"
X = pd.read_csv(newtest, index_col=0)
X = X['Processed Review'].tolist()
from keras import Sequential
from keras.layers import LSTM
vectorizer = TfidfVectorizer(max_features=77)
vectorizer.fit(X)
vectorizer.transform(X)
#vectorizer.transform(Y)
tfidf_vector_X = vectorizer.transform(X).toarray() #shape - (3,6)
#tfidf_vector_Y = vectorizer.transform(Y).toarray() #shape - (3,6)
tfidf_vector_X = tfidf_vector_X[:, :, None] #shape - (3,6,1) since LSTM cells expects ndims = 3
#tfidf_vector_Y = tfidf_vector_Y[:, :, None] #shape - (3,6,1)
model = load_model('lstm_model.h5')
data = np.array(tfidf_vector_X)
#print(data.shape)


#data.shape
# make predictions

yhat = model.predict(data, verbose=0)
yhat.shape
print(yhat)


Using TensorFlow backend.


Instructions for updating:
Colocations handled automatically by placer.
Instructions for updating:
Use tf.cast instead.
[[[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [ 4.87214536e-04]
  [ 4.89889120e-04]
  [ 4.82698873e-04]]

 [[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [ 2.04028605e-04]
  [ 2.97483726e-04]
  [ 3.65652319e-04]]

 [[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [ 7.14426511e-04]
  [ 6.89077191e-04]
  [ 6.56357210e-04]]

 ...

 [[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [ 1.13690774e-07]
  [ 9.14906266e-08]
  [ 7.33453049e-08]]

 [[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [ 1.60176565e-08]
  [ 1.14892797e-08]
  [ 7.76302844e-09]]

 [[-3.45818352e-09]
  [-5.71893999e-09]
  [-7.18762561e-09]
  ...
  [-9.71488134e-09]
  [-9.71488134e-09]
  [-9.71488134e-09]]]


In [25]:
y = vectorizer.get_feature_names()
print(y)

['asp', 'best', 'class', 'comparison', 'control', 'create', 'cs', 'error', 'file', 'form', 'generate', 'get', 'inside', 'java', 'javascript', 'know', 'library', 'linq', 'load', 'log', 'make', 'multiline', 'multiple', 'mvc', 'mysql', 'net', 'newline', 'ntlm', 'number', 'object', 'odd', 'one', 'open', 'oracle', 'outlook', 'oversee', 'package', 'pagination', 'pair', 'panel', 'pas', 'perl', 'permission', 'php', 'plane', 'platform', 'point', 'populate', 'print', 'process', 'program', 'programmatically', 'provider', 'python', 'query', 'quick', 'race', 'raw', 'read', 'record', 'recursive', 'redundant', 'register', 'replication', 'sql', 'status', 'stop', 'studio', 'subversion', 'suggestion', 'suppress', 'svn', 'system', 'test', 'use', 'way', 'wcf']


In [28]:
k = " asp best class comparison"
p = k.split(" ")

dicted = {}

for i in range(len(y)):
  k = y[i]
  dicted[k] = 0
  
print(dicted)


p.remove("")
    

for i in p:
  if i in dicted.keys():
    dicted[i] = dicted[i] + 1
  
    
    
  
      

print(dicted)

{'asp': 0, 'best': 0, 'class': 0, 'comparison': 0, 'control': 0, 'create': 0, 'cs': 0, 'error': 0, 'file': 0, 'form': 0, 'generate': 0, 'get': 0, 'inside': 0, 'java': 0, 'javascript': 0, 'know': 0, 'library': 0, 'linq': 0, 'load': 0, 'log': 0, 'make': 0, 'multiline': 0, 'multiple': 0, 'mvc': 0, 'mysql': 0, 'net': 0, 'newline': 0, 'ntlm': 0, 'number': 0, 'object': 0, 'odd': 0, 'one': 0, 'open': 0, 'oracle': 0, 'outlook': 0, 'oversee': 0, 'package': 0, 'pagination': 0, 'pair': 0, 'panel': 0, 'pas': 0, 'perl': 0, 'permission': 0, 'php': 0, 'plane': 0, 'platform': 0, 'point': 0, 'populate': 0, 'print': 0, 'process': 0, 'program': 0, 'programmatically': 0, 'provider': 0, 'python': 0, 'query': 0, 'quick': 0, 'race': 0, 'raw': 0, 'read': 0, 'record': 0, 'recursive': 0, 'redundant': 0, 'register': 0, 'replication': 0, 'sql': 0, 'status': 0, 'stop': 0, 'studio': 0, 'subversion': 0, 'suggestion': 0, 'suppress': 0, 'svn': 0, 'system': 0, 'test': 0, 'use': 0, 'way': 0, 'wcf': 0}
{'asp': 1, 'best':

In [0]:
'''for i in range(61):
  for j in range(77):
    if yhat[i,j] >= 0:
      print (yhat[i,j])'''

listed = []
for i in range(len(yhat[0])):
  listed.append(yhat[0][i][0])
  
  

max_value = max(listed)
max_value

max_index = listed.index(max_value)
max_index
print(max_value , y[max_index])



0.0009734803 oracle


In [0]:
import re
import csv
import operator
from collections import defaultdict

all_tags = ['asp', 'best', 'class', 'comparison', 'control', 'create', 'cs', 'error', 'file', 'form', 'generate', 'get', 'inside', 'java', 'javascript', 'know', 'library', 'linq', 'load', 'log', 'make', 'multiline', 'multiple', 'mvc', 'mysql', 'net', 'newline', 'ntlm', 'number', 'object', 'odd', 'one', 'open', 'oracle', 'outlook', 'oversee', 'package', 'pagination', 'pair', 'panel', 'pas', 'perl', 'permission', 'php', 'plane', 'platform', 'point', 'populate', 'print', 'process', 'program', 'programmatically', 'provider', 'python', 'query', 'quick', 'race', 'raw', 'read', 'record', 'recursive', 'redundant', 'register', 'replication', 'sql', 'status', 'stop', 'studio', 'subversion', 'suggestion', 'suppress', 'svn', 'system', 'test', 'use', 'way', 'wcf'] 

#'fluid-dynamics', 'gravity', 'energy', 'particle-physics', 'electrostatics', 'cosmology', 'visible-light', 'statistical-mechanics', 'waves', 'black-holes', 'electricity', 'newtonian-gravity', 'electromagnetic-radiation', 'condensed-matter', 'experimental-physics', 'kinematics', 'photons', 'magnetic-fields', 'string-theory', 'lagrangian-formalism', 'spacetime', 'electric-circuits', 'mathematical-physics', 'mass', 'angular-momentum', 'differential-geometry', 'speed-of-light', 'solid-state-physics', 'pressure', 'operators', 'energy-conservation', 'nuclear-physics', 'momentum', 'electrons', 'rotational-dynamics', 'quantum-information', 'astrophysics', 'soft-question', 'astronomy', 'resource-recommendations', 'reference-frames', 'wavefunction', 'acoustics', 'temperature', 'conservation-laws', 'orbital-motion', 'hilbert-space', 'acceleration', 'time', 'friction', 'atomic-physics', 'quantum-spin', 'terminology', 'electric-fields', 'electric-current', 'schroedinger-equation', 'entropy', 'everyday-life', 'symmetry', 'water', 'charge', 'work', 'potential', 'universe', 'electrical-resistance', 'quantum-electrodynamics', 'velocity', 'standard-model', 'harmonic-oscillator', 'vectors', 'metric-tensor', 'gauge-theory', 'potential-energy', 'space-expansion', 'hamiltonian-formalism', 'field-theory', 'supersymmetry', 'relativity', 'material-science', 'radiation', 'entanglement', 'capacitance', 'collision', 'renormalization', 'laser', 'semiconductor-physics', 'reflection', 'group-theory', 'scattering', 'quantum-gravity', 'uncertainty-principle', 'research-level', 'earth', 'education', 'voltage', 'simulation', 'big-bang', 'measurement', 'torque', 'projectile', 'superconductivity', 'computational-physics', 'double-slit-experiment', 'units', 'conformal-field-theory', 'refraction', 'classical-electrodynamics', 'conventions', 'curvature', 'frequency', 'thermal-radiation', 'gravitational-waves', 'gauss-law', 'tensor-calculus', 'atmospheric-science', 'history', 'vacuum', 'coordinate-systems', 'definition', 'fourier-transform', 'inertial-frames', 'atoms', 'quantum-interpretations', 'probability', 'planets', 'ideal-gas', 'measurement-problem', 'path-integral', 'rotation', 'physical-chemistry', 'notation', 'faster-than-light', 'polarization', 'mass-energy', 'spring', 'interference', 'drag', 'feynman-diagram', 'maxwell-equations', 'rotational-kinematics', 'fermions', 'group-representations', 'quantum-chromodynamics', 'dark-matter', 'air', 'geometric-optics', 'geometry', 'spectroscopy', 'variational-principle', 'mathematics', 'power', 'aerodynamics', 'biophysics', 'diffraction', 'sun', 'hamiltonian', 'home-experiment', 'quantum-optics', 'quantum-computer', 'phase-transition', 'antimatter', 'neutrinos', 'integration', 'differentiation', 'specific-reference', 'time-dilation', 'dimensions', 'higgs', 'representation-theory', 'speed', 'solar-system', 'space', 'stars', 'lie-algebra', 'wave-particle-duality', 'symmetry-breaking', 'free-body-diagram', 'dirac-equation', 'boundary-conditions', 'commutator', 'dimensional-analysis', 'oscillators', 'topology', 'observers', 'density', 'spinors', 'action', 'heat', 'rocket-science', 'event-horizon', 'causality', 'singularities', 'perturbation-theory', 'elasticity', 'vector-fields', 'galaxies', 'estimation', 'tensors', 'centripetal-force', 'flow', 'resonance', 'stress-energy-tensor', 'linear-algebra', 'noethers-theorem', 'cosmological-inflation', 'moment-of-inertia', 'lenses', 'surface-tension', 'celestial-mechanics', 'plasma-physics', 'rigid-body-dynamics', 'error-analysis', 'radioactivity', 'quarks', 'crystals', 'physical-constants', 'ads-cft', 'relative-motion', 'statics', 'conductors', 'lorentz-symmetry', 'induction', 'hydrogen', 'software', 'dark-energy', 'coulombs-law', 'equilibrium', 'wavelength', 'superposition', 'geodesics', 'angular-velocity', 'buoyancy', 'eigenvalue', 'continuum-mechanics', 'electronic-band-theory', 'complex-numbers', 'centrifugal-force', 'discrete', 'geophysics', 'many-body', 'string', 'gauge-invariance', 'stress-strain', 'photoelectric-effect', 'statistics', 'fusion', 'electronics', 'dielectric', 'differential-equations', 'large-hadron-collider', 'vibration', 'observables', 'hydrostatics', 'cmb', 'density-operator', 'calculus', 'kinetic-theory', 'interactions', 'molecules', 'topological-field-theory', 'hawking-radiation', 'inductance', 'information', 'thermal-conductivity', 'free-fall', 'moon', 'diffusion', 'popular-science', 'batteries', 'topological-order', 'electrical-engineering', 'doppler-effect', 'approximations', 'metals', 'viscosity', 'covariance', 'greens-functions', 'distributions', 'particles', 'tidal-effect', 'neutrons', 'equivalence-principle', 'yang-mills', 'topological-insulators', 'vision', 'regularization', 'correlation-functions', 'constrained-dynamics', 'inertia', 'klein-gordon-equation', 'si-units', 'virtual-particles', 'bose-einstein-condensate', 'experimental-technique', 'data-analysis', 'second-quantization', 'wavefunction-collapse', 'distance', 'magnetic-moment', 'elementary-particles', 'beyond-the-standard-model', 'determinism', 'weak-interaction', 'protons', 'stability', 'fluid-statics', 'ising-model', 'nuclear-engineering', 'phase-space', 'weight', 'pauli-exclusion-principle', 'quantization', 'telescopes', 'unit-conversion', 'turbulence', 'time-evolution', 'magnetic-monopoles', 'degrees-of-freedom', 'evaporation', 'bernoulli-equation', 'propagator', 'scattering-cross-section', 'reversibility', 'partition-function', 'variational-calculus', 'chaos-theory', 'branes', 'matter', 'parity', 'states-of-matter', 'lattice-model', 'satellites', 'signal-processing', 'time-reversal-symmetry', 'decoherence', 'dipole', 'space-travel', 'quantum-anomalies', 'x-rays', 'aircraft', 'navier-stokes', 'interferometry', 'absorption', 'unitarity', 'adiabatic', 'graphene', 'thought-experiment', 'quantum-hall-effect', 'neutron-stars', 'higgs-boson', 'time-travel', 'phonons', 'non-linear-systems', 'radio', 'volume', 'orbitals', 'bosons', 's-matrix-theory', 'antennas', 'electroweak', 'ice', 'binding-energy', 'perpetual-motion', 'supergravity', 'holographic-principle', 'molecular-dynamics', 'metrology', 'gauge', 'compactification', 'lightning', 'quantum-chemistry', 'quantum-tunneling', 'wormholes', 'models', 'chirality', 'electromagnetic-induction', 'bells-inequality', 'explosions', 'nanoscience', 'particle-detectors', 'renewable-energy', 'weather', 'observational-astronomy', 'majorana-fermions', 'gamma-rays', 'dispersion', 'cosmological-constant', 'locality', 'ligo', 'gyroscopes', 'biology', 'vortex', 'strong-force', 'dirac-matrices', 'microscopy', 'classical-field-theory', 'stellar-physics', 'qft-in-curved-spacetime', 'propulsion', 'eye', 'heat-engine', 'fiber-optics', 'non-equilibrium', 'normalization', 'wick-rotation', 'convection', 'applied-physics', 'coherence', 'magnetostatics', 'perception', 'subatomic', 'theory-of-everything', 'superfluidity', 'light-emitting-diodes', 'duality', 'chern-simons-theory', 'noise', 'poincare-symmetry', 'poisson-brackets', 'supernova', 'gas', 'coriolis-effect', 'accelerator-physics', 'microwaves', 'coupled-oscillators', 'dipole-moment', 'spin-statistics', 'non-linear-optics', 'lift', 'radio-frequency', 'semiclassical', 'multipole-expansion', 'galilean-relativity', 'infrared-radiation', 'dissipation', 'effective-field-theory', 'gravitational-lensing', 'x-ray-crystallography', 'multiverse', 'gravitational-redshift', 'grassmann-numbers', 'photon-emission', 'topological-phase', 'chemical-potential', 'arrow-of-time', 'elements', 'helicity', 'precession', 'solid-mechanics', 'kaluza-klein', 'escape-velocity', 'blackbody', 'complex-systems', 'moment', 'brownian-motion', 'cp-violation', 'cooling', 'displacement', 'stellar-evolution', 'observable-universe', 'light', 'instantons', 'general-physics', 'numerical-method', 'data', 'wick-theorem', 'identical-particles', 'imaging', 'levitation', 'exoplanets', 'electrochemistry', 'born-rule', 'carnot-cycle', 'carrier-particles', 'aether', 'casimir-effect', 'confinement', 'climate-science', 'optical-materials', 'point-particle', 'warp-drives', 'anti-de-sitter-spacetime', 'linear-systems', 'foundations', 'teleportation', 'photovoltaics', 'quantum-statistics', 'meteorology', 'anyons', 'berry-pancharatnam-phase', 'bubble', 'cosmic-rays', 'visualization', 'solitons', 'poynting-vector', 'experimental-technology', 'camera', 'asteroids', 'loop-quantum-gravity', 'non-perturbative', 'grand-unification', 'integrable-systems', 'spin-model', 'spherical-harmonics', 'pair-production', 'non-locality', 'gluons', 'functional-derivatives', 'randomness', 'freezing', 'laws-of-physics', 'critical-phenomena', 'structural-beam', 'tachyon', 'textbook-erratum', 'mesons', 'material', 'ground-state', 'isotope', 'jerk', 'harmonics', 'brst', 'space-mission', 'pions', 'waveguide', 'scaling', 'isospin-symmetry', 'ions', 'gauge-symmetry', 'kerr-metric', 'hologram', 'black-hole-thermodynamics', 'capillary-action', 'shockwave', 'scale-invariance', 'redshift', 'particle-accelerators', 'chemical-compounds', 'medical-physics', 'milky-way', 'cold-atoms', 'stochastic-processes', 'color-charge', 'algorithm', 'order-of-magnitude', 'insulators', 'humidity', 'galaxy-rotation-curve', 'luminosity', 'condensation', 'density-functional-theory', 'epr-experiment', 'effective-action', 'trace', 'tight-binding', 'thermoelectricity', 'unified-theories', 'twin-paradox', 'sensor', 'baryons', 'absolute-units', 'fine-tuning', 'higgs-mechanism', 'invariants', 'ghosts', 'combustion', 'cpt-symmetry', 'quasiparticles', 'virtual-photons', 'density-of-states', 'clifford-algebra', 'normal-modes', 'numerics', 'magnetohydrodynamics', 'geomagnetism', 'ionization-energy', 'technology', 'piezoelectric', 'phase-diagram', 'quantum-states', 'machs-principle', 'matrix-elements', 'leptons', 'anticommutator', 'fermis-golden-rule', 'length-contraction', 'solar-system-exploration', 'white-holes', 'scales', 'physics-careers', 'big-list', 'computer', 'entanglement-entropy', 'phase-velocity', 'solar-wind', 'spin-chains', 'wigner-transform', 'solar-cells', 'diffeomorphism-invariance', 'asymptotics', 'non-linear-dynamics', 'modified-gravity', 'nasa', 'instrument', 'analyticity', 'category-theory', 'conservative-field', 'efficient-energy-use', 'ward-identity', 'schroedingers-cat', 'superalgebra', 'de-sitter-spacetime', 'cellular-automaton', 'optimization', 'open-quantum-systems', 'meteors', 'gps', 'fractals', 'baryogenesis', 'black-hole-firewall', 'raman-spectroscopy', 'plane-wave', 'superconformality', 'charge-conjugation', 'equations-of-motion', 'boundary-terms', 'linearized-theory', 'synchrotron-radiation', 'plasmon', 'radiometry', 'virial-theorem', 'wilson-loop', 'jupiter', 'laser-interaction', 'matrix-model', 'nucleosynthesis', 'moduli', 'image-processing', 'fan', 'calabi-yau', 'fluctuation-dissipation', 'stochastic-models', 'string-theory-landscape', 'inert-gases', 'integrals-of-motion', 'comets', 'clock', 'faq', 'cryogenics', 'laboratory-safety', 'mssm', 'oceanography', 'short-circuits', 'proton-decay', 'gravitational-collapse', 'exotic-matter', 'eclipse', 'graph-theory', 'pulsars', 'sigma-models', 'galaxy-clusters', 'dimensional-reg', 'atomic-excitation', 'anharmonic-oscillators', 'anthropic-principle', 'emergent-properties', 'energy-storage', 'interstellar-matter', 'low-temperature-physics', 'shadow', 'superspace-formalism', 'twistor', 'unruh-effect', 'minkowski-space', 'internal-energy', 'disorder', 'design', 'astrophotography', 'cavity-qed', 'interstellar-travel', 'lienard-wiechert', 'sports', 'rigid-solid', 'radar', 'relativistic-jets', 'photometry', 'structure-formation', 'network', 'higgs-field', 'fermi-liquids', 'cold-fusion', 'algebraic-geometry', 'dirac-monopole', 'equation-of-state', 'exchange-interaction', 'earthquake', 'cherenkov-radiation', 'building-physics', 'fluorescence', 'higher-spin', 'nature', 'string-field-theory', 'three-body-problem', 'percolation', 'meteorites', 'half-life', 'epistemology', 'adhesion', 'food', 'mean-free-path', 'porous-media', 'runge-lenz-vector', 'strong-correlated', 'reissner-nordstrom-metric', 'newtonian-fluid', 'length', 'frame-dragging', 'hadron-dynamics', 'accretion-disk', 'brachistochrone-problem', 'axion', 'functional-determinants', 'fock-space', 'liquid-crystal', 'non-commutative-geometry', 'nuclei', 'soft-matter', 'positronium', 'poincare-recurrence', 'steady-state', 'special-functions', 'thermal-field-theory', 'self-energy', 'quark-gluon-plasma', 'heavy-ion', 'bloch-sphere', 'braggs-law', 'deformation-quantization', 'diamond', 'closed-timelike-curve', 'bohmian-mechanics', 'binary-stars', 'leptogenesis', 'metallicity', 'potential-flow', 'stellar-population', 'maxwell-relations', 'non-linear-schroedinger', 'parallax', 'osmosis', 'amorphous-solids', 'canonical-conjugation', 'cosmic-censorship', 'dynamical-systems', 'displacement-current', 'bosonization', 'anderson-localization', 'astrometrics', 'atomic-clocks', 'non-commutative-theory', 'liquid-state', 'glass', 'topological-entropy', 'quasars', 'spin-glass', 'white-dwarfs', 'josephson-junction', 'ion-traps', 'large-n', 'metric-space', 'nucleation', 'born-oppenheimer-approx', 'amplituhedron', 'dirac-string', 'enthalpy', 'optical-lattices', 'nebulae', 'light-pollution', 'isotropy', 'gravitational-potential', 'unruh-radiation', 'two-level-system', 'seiberg-witten-theory', 'radiation-pressure', 'tsunami', 'solar-sails', 'wimps', 'isentropic', 'kerr-newman-metric', 'mass-spectrometry', 'cpt-violation', 'bloch-oscillation', 'bao', 'central-charge', 'debye-length', 'ferromagnetism', 'meteoroids', 'mnemonic', 'hadronization', 'grav-wave-detectors', 'geometric-topology', 'floquet-theory', 'supersymmetric-particles', 'transit', 'tevatron', 'quasicrystals', 'rheology', 'weak-lensing', 'fracture', 'gauss-bonnet', 'granulated-materials', 'nuclear-structure', 'magnets', 'lamb-shift', 'electromagnetic-field', 'cosmic-string', 'ballistics', 'birrefringence', 'landauers-principle', 'non-gaussianity', 'frw-universe', 'wightman-fields', 'wetting', 'reflectance', 'spin-liquid', 'sine-gordon', 'stellar-wind', 'rabi-model', 'free-electron-lasers', 'hopf-algebra', 'impedance-spectroscopy', 'irreversible', 'bifurcation', 'brown-dwarfs', 'correspondence-principle', 'couette-flow', 'econo-physics', 'duration', 'chirp', 'backscattering', 'affine-lie-algebra', 'antimatter-storage', 'pentaquarks', 'synthetic-gauge-fields', 'spin-ice', 'topological-charges', 'quasi-periodic', 'self-capacitance', 'feedback', 'heterotic-string', 'lamb-waves', 'logic-gates', 'machos']
all_tags = set(all_tags)


in_file = open("Test100.csv")
out_file = open("final.csv", "w")
reader = csv.DictReader(in_file)
writer = csv.writer(out_file)
writer.writerow(['id','tags'])

def f1_score(tp, fp, fn):
    p = (tp*1.) / (tp+fp)
    r = (tp*1.) / (tp+fn)
    f1 = (2*p*r)/(p+r)
    return f1

def clean_html(raw_html):
    cleanr = re.compile('<.*?>')
    cleantext = re.sub(cleanr, '', raw_html)
    return cleantext

def get_words(text):
    word_split = re.compile('[^a-zA-Z0-9_\\+\\-/]')
    return [word.strip().lower() for word in word_split.split(text)]
	
top_tags = ['C', 'C++', 'Java', 'JavaScript', 'C#', 'php', 'android', 'jquery', 'python', 'html', 'ios']
for ind, row in enumerate(reader):
    text = clean_html(row["Title"])
    tfrequency_dict = defaultdict(int)
    word_count = 0.
    for word in get_words(text):
        if word.isalpha() and word in all_tags:
            tfrequency_dict[word] += 1
            word_count += 1.
    for word in tfrequency_dict:
    	tf = tfrequency_dict[word] / word_count
    	tfrequency_dict[word] = tf 
    pred_title_tags = sorted(tfrequency_dict, key=tfrequency_dict.get, reverse=True)[:10]
    print(pred_title_tags)
    
    text = clean_html(row["Body"])
    dfrequency_dict = defaultdict(int)
    word_count = 0.
    for word in get_words(text):
        if word.isalpha() and word in all_tags:
            dfrequency_dict[word] += 1
            word_count += 1.
    for word in dfrequency_dict:
    	tf = dfrequency_dict[word] / word_count
    	dfrequency_dict[word] = tf 
    pred_content_tags = sorted(dfrequency_dict, key=dfrequency_dict.get, reverse=True)[:10]
    #print(pred_content_tags)
    pred_tags_dict = {}
    for word in set(pred_title_tags + pred_content_tags):
    	pred_tags_dict[word] = tfrequency_dict.get(word,0) + dfrequency_dict.get(word,0)
    pred_tags = set(sorted(pred_tags_dict, key=pred_tags_dict.get, reverse=True)[:3])
    
    
    length = len(pred_tags)
    for tag in top_tags[:3 - length]:
        pred_tags.add(tag)
    
    writer.writerow([row['Title'], " ".join(pred_tags)])
    if ind%50000 == 0:
    	print("Processed : ", ind)

['linq', 'sql', 'load', 'one']
Processed :  0
[]
['error', 'net']
['stop']
['pagination']
['best', 'way', 'package']
['suppress', 'ntlm']
['point']
[]
['control', 'subversion']
['java']
[]
['get']
['test']
['know', 'plane']
['java']
[]
['newline', 'asp', 'net']
['asp', 'net', 'mvc']
['studio']
['javascript', 'error']
['mysql', 'log', 'replication']
['test', 'object']
['inside', 'panel']
['way', 'use', 'linq', 'oracle']
[]
['error']
['control', 'open']
['form']
['outlook', 'multiple']
[]
['create', 'subversion']
['python']
['php']
['library']
['net', 'raw']
['make', 'know', 'class']
['create']
['race']
['best', 'python']
['pair', 'program']
[]
['file', 'perl']
['comparison', 'javascript']
['programmatically', 'file']
[]
[]
['status']
['get', 'record']
['print']
['mysql', 'oversee']
['python']
['class']
[]
[]
['wcf']
['svn']
[]
[]
['comparison']
[]
